"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* tslint:disable */
require('./TilesList.module.css');
var styles = {
    filePicker: 'filePicker_a5dfbc3b',
    tabsContainer: 'tabsContainer_a5dfbc3b',
    tabContainer: 'tabContainer_a5dfbc3b',
    nav: 'nav_a5dfbc3b',
    tabHeaderContainer: 'tabHeaderContainer_a5dfbc3b',
    breadcrumbNav: 'breadcrumbNav_a5dfbc3b',
    breadcrumbNavItem: 'breadcrumbNavItem_a5dfbc3b',
    tab: 'tab_a5dfbc3b',
    tabFiles: 'tabFiles_a5dfbc3b',
    scrollablePaneWrapper: 'scrollablePaneWrapper_a5dfbc3b',
    actionButtonsContainer: 'actionButtonsContainer_a5dfbc3b',
    actionButtons: 'actionButtons_a5dfbc3b',
    actionButton: 'actionButton_a5dfbc3b',
    tabHeader: 'tabHeader_a5dfbc3b',
    selectedTab: 'selectedTab_a5dfbc3b',
    header: 'header_a5dfbc3b',
    xlg: 'xlg_a5dfbc3b',
    xxlg: 'xxlg_a5dfbc3b',
    xxxlg: 'xxxlg_a5dfbc3b',
    xxxxlg: 'xxxxlg_a5dfbc3b',
    itemPickerTopBar: 'itemPickerTopBar_a5dfbc3b',
    commandBarNoChevron: 'commandBarNoChevron_a5dfbc3b',
    fileItem: 'fileItem_a5dfbc3b',
    folderItem: 'folderItem_a5dfbc3b',
    fileTypeIcon: 'fileTypeIcon_a5dfbc3b',
    fileTypeIconIcon: 'fileTypeIconIcon_a5dfbc3b',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_a5dfbc3b',
    iconColumnHeader: 'iconColumnHeader_a5dfbc3b',
    fileRow: 'fileRow_a5dfbc3b',
    folderRow: 'folderRow_a5dfbc3b',
    emptyFolder: 'emptyFolder_a5dfbc3b',
    emptyFolderImage: 'emptyFolderImage_a5dfbc3b',
    emptyFolderImageTag: 'emptyFolderImageTag_a5dfbc3b',
    emptyFolderTitle: 'emptyFolderTitle_a5dfbc3b',
    emptyFolderSubText: 'emptyFolderSubText_a5dfbc3b',
    emptyFolderMobile: 'emptyFolderMobile_a5dfbc3b',
    emptyFolderPc: 'emptyFolderPc_a5dfbc3b',
    emptyFolderIcon: 'emptyFolderIcon_a5dfbc3b',
    aboveNameplate: 'aboveNameplate_a5dfbc3b',
    tileContent: 'tileContent_a5dfbc3b',
    foreground: 'foreground_a5dfbc3b',
    grid: 'grid_a5dfbc3b',
    cellContent: 'cellContent_a5dfbc3b',
    content: 'content_a5dfbc3b',
    tile: 'tile_a5dfbc3b',
    invokable: 'invokable_a5dfbc3b',
    namePlate: 'namePlate_a5dfbc3b',
    nameplate: 'nameplate_a5dfbc3b',
    name: 'name_a5dfbc3b',
    isLarge: 'isLarge_a5dfbc3b',
    activity: 'activity_a5dfbc3b',
    signalField: 'signalField_a5dfbc3b',
    compact: 'compact_a5dfbc3b',
    signalFieldValue: 'signalFieldValue_a5dfbc3b',
    folderList: 'folderList_a5dfbc3b',
    link: 'link_a5dfbc3b',
    cell: 'cell_a5dfbc3b',
    listCell: 'listCell_a5dfbc3b',
    label: 'label_a5dfbc3b',
    check: 'check_a5dfbc3b',
    selectable: 'selectable_a5dfbc3b',
    showCheck: 'showCheck_a5dfbc3b',
    selected: 'selected_a5dfbc3b',
    dialogMainOverride: 'dialogMainOverride_a5dfbc3b',
    itemTileBlankCover: 'itemTileBlankCover_a5dfbc3b',
    metadata: 'metadata_a5dfbc3b',
    isSmall: 'isSmall_a5dfbc3b',
    listPage: 'listPage_a5dfbc3b',
    odItemTile2FolderCover: 'odItemTile2FolderCover_a5dfbc3b',
    standaloneListBreadcrumb: 'standaloneListBreadcrumb_a5dfbc3b',
};
exports.default = styles;
/* tslint:enable */ 

//# sourceMappingURL=TilesList.module.scss.js.map
