"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* tslint:disable */
require('./RecentFilesTab.module.css');
var styles = {
    filePicker: 'filePicker_2c43fa6a',
    tabsContainer: 'tabsContainer_2c43fa6a',
    tabContainer: 'tabContainer_2c43fa6a',
    nav: 'nav_2c43fa6a',
    tabHeaderContainer: 'tabHeaderContainer_2c43fa6a',
    breadcrumbNav: 'breadcrumbNav_2c43fa6a',
    breadcrumbNavItem: 'breadcrumbNavItem_2c43fa6a',
    tab: 'tab_2c43fa6a',
    tabFiles: 'tabFiles_2c43fa6a',
    scrollablePaneWrapper: 'scrollablePaneWrapper_2c43fa6a',
    actionButtonsContainer: 'actionButtonsContainer_2c43fa6a',
    actionButtons: 'actionButtons_2c43fa6a',
    actionButton: 'actionButton_2c43fa6a',
    tabHeader: 'tabHeader_2c43fa6a',
    selectedTab: 'selectedTab_2c43fa6a',
    header: 'header_2c43fa6a',
    xlg: 'xlg_2c43fa6a',
    xxlg: 'xxlg_2c43fa6a',
    xxxlg: 'xxxlg_2c43fa6a',
    xxxxlg: 'xxxxlg_2c43fa6a',
    itemPickerTopBar: 'itemPickerTopBar_2c43fa6a',
    commandBarNoChevron: 'commandBarNoChevron_2c43fa6a',
    fileItem: 'fileItem_2c43fa6a',
    folderItem: 'folderItem_2c43fa6a',
    fileTypeIcon: 'fileTypeIcon_2c43fa6a',
    fileTypeIconIcon: 'fileTypeIconIcon_2c43fa6a',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_2c43fa6a',
    iconColumnHeader: 'iconColumnHeader_2c43fa6a',
    fileRow: 'fileRow_2c43fa6a',
    folderRow: 'folderRow_2c43fa6a',
    emptyFolder: 'emptyFolder_2c43fa6a',
    emptyFolderImage: 'emptyFolderImage_2c43fa6a',
    emptyFolderImageTag: 'emptyFolderImageTag_2c43fa6a',
    emptyFolderTitle: 'emptyFolderTitle_2c43fa6a',
    emptyFolderSubText: 'emptyFolderSubText_2c43fa6a',
    emptyFolderMobile: 'emptyFolderMobile_2c43fa6a',
    emptyFolderPc: 'emptyFolderPc_2c43fa6a',
    emptyFolderIcon: 'emptyFolderIcon_2c43fa6a',
    gridListCell: 'gridListCell_2c43fa6a',
    cellRight: 'cellRight_2c43fa6a',
    cellLastRow: 'cellLastRow_2c43fa6a',
    itemTile: 'itemTile_2c43fa6a',
    isFile: 'isFile_2c43fa6a',
    isPhoto: 'isPhoto_2c43fa6a',
    isVideo: 'isVideo_2c43fa6a',
    hasThumbnail: 'hasThumbnail_2c43fa6a',
    itemTileContent: 'itemTileContent_2c43fa6a',
    itemTileDiscoverFileContainer: 'itemTileDiscoverFileContainer_2c43fa6a',
    itemTileFileContainer: 'itemTileFileContainer_2c43fa6a',
    itemTileFile: 'itemTileFile_2c43fa6a',
    itemTileThumbnail: 'itemTileThumbnail_2c43fa6a',
    image: 'image_2c43fa6a',
    itemTileCheckCircle: 'itemTileCheckCircle_2c43fa6a',
    isSelected: 'isSelected_2c43fa6a',
    itemTileNamePlate: 'itemTileNamePlate_2c43fa6a',
    itemTileName: 'itemTileName_2c43fa6a',
    itemTileChildCount: 'itemTileChildCount_2c43fa6a',
    itemTileSubText: 'itemTileSubText_2c43fa6a',
    recentGridList: 'recentGridList_2c43fa6a',
};
exports.default = styles;
/* tslint:enable */ 

//# sourceMappingURL=RecentFilesTab.module.scss.js.map
